### ISSUE TITLE
undefined templates in component_v2.js

### ISSUE THREAD

**Issue by parveen1112** [js-factory/hoc#4] opened 2019-03-27 19:53 UTC
[component_v2.js](https://github.com/js-factory/hoc/blob/master/integration/preact/component_v2.js)
templates not defined
this.render = (props) => {
                    const view = template || templates || InnerComponent;
                    return h(view, this.mergeProps());
};

**Comment by upendradevsingh** [comment] 2019-04-17 11:31
The issue is fixed and merged.

**Closed by upendradevsingh** 2019-04-17 11:31 UTC
Labels: bug
